dist: trusty
sudo: false
group: beta
language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

jobs:
  # XXX fast_finish doesn't work with stages yet. See
  # https://github.com/travis-ci/travis-ci/issues/8425
  # --elopio - 20180531
  fast_finish: true
  allow_failures:
    - env: SOLC_NIGHTLY=true
  include:
    - stage: tests
      name: "Linter"
      script: npm run lint

    - stage: tests
      name: "Unit tests"
      script: npm run sc_test

    - stage: tests
      name: "Unit tests with coverage report"
      script: npm run sc_test
      env: SOLIDITY_COVERAGE=true

    - stage: tests
      name: "Unit tests using solc nightly"
      script: npm run sc_test
      env: SOLC_NIGHTLY=true
